server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # Apuntamos al contenedor de Keycloak
          jwk-set-uri: http://paymentchain-keycloak:8080/realms/paymentchain-realm/protocol/openid-connect/certs

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:

        - id: customer-service
          uri: lb://businessdomain-customer
          predicates:
            - Path=/customers/**

        - id: transaction-service-transactions
          uri: lb://businessdomain-transaction
          predicates:
            - Path=/transactions/**

        - id: transaction-service-accounts
          uri: lb://businessdomain-transaction
          predicates:
            - Path=/accounts/**


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: 'Transacciones'
        url: /v3/api-docs/transaction
      - name: 'Clientes'
        url: /v3/api-docs/customer
      - name: 'Notificaciones'
        url: /v3/api-docs/notification