server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # Apuntamos al contenedor de Keycloak
          jwk-set-uri: http://paymentchain-keycloak:8080/realms/paymentchain-realm/protocol/openid-connect/certs

  cloud:
    gateway:
      server:
        webflux:
          # Configuración de Discovery (Eureka)
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          # Definición de Rutas
          routes:
            - id: customer-service
              uri: lb://businessdomain-customer
              predicates:
                - Path=/customers/**

            - id: transaction-service
              uri: lb://businessdomain-transaction
              predicates:
                - Path=/transactions/**, /accounts/**

            - id: transaction-docs
              uri: lb://businessdomain-transaction
              predicates:
                - Path=/v3/api-docs/transaction
              filters:
                - RewritePath=/v3/api-docs/transaction, /v3/api-docs

                - id: customer-docs
                  uri: lb://businessdomain-customer
                  predicates:
                    - Path=/v3/api-docs/customer
                  filters:
                    - RewritePath=/v3/api-docs/customer, /v3/api-docs

                - id: notification-docs
                  uri: lb://notification-service
                  predicates:
                    - Path=/v3/api-docs/notification
                  filters:
                    - RewritePath=/v3/api-docs/notification, /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: 'Transacciones'
        url: /v3/api-docs/transaction
      - name: 'Clientes'
        url: /v3/api-docs/customer
      - name: 'Notificaciones'
        url: /v3/api-docs/notification