server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # Apuntamos al contenedor de Keycloak
          jwk-set-uri: http://paymentchain-keycloak:8080/realms/paymentchain-realm/protocol/openid-connect/certs

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:

            - id: customer-service
              uri: lb://businessdomain-customer
              predicates:
                - Path=/customers/**

            - id: transaction-service
              uri: lb://businessdomain-transaction
              predicates:
                - Path=/transactions/**, /accounts/**

            # Swagger Transaction
            - id: transaction-docs
              uri: lb://businessdomain-transaction
              predicates:
                - Path=/v3/api-docs/transaction
              filters:
                - RewritePath=/v3/api-docs/transaction(?<segment>/?.*), /v3/api-docs${segment}

            # Swagger Customer
            - id: customer-docs
              uri: lb://businessdomain-customer
              predicates:
                - Path=/v3/api-docs/customer
              filters:
                - RewritePath=/v3/api-docs/customer(?<segment>/?.*), /v3/api-docs${segment}

            # Swagger Notification
            - id: notification-docs
              uri: lb://notification-service
              predicates:
                - Path=/v3/api-docs/notification
              filters:
                - RewritePath=/v3/api-docs/notification(?<segment>/?.*), /v3/api-docs${segment}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: 'Transacciones'
        url: /v3/api-docs/transaction
      - name: 'Clientes'
        url: /v3/api-docs/customer
      - name: 'Notificaciones'
        url: /v3/api-docs/notification