server:
  port: 8090

spring:
  application:
    name: currency-exchange
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  # Configuración de Redis
  data:
    redis:
      host: paymentchain-redis # Nombre del servicio en Docker Compose
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1 Hora

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

# Configuración de Resilience4j (El Cortacircuitos)
resilience4j:
  circuitbreaker:
    instances:
      externalApi:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10         # Analiza las últimas 10 peticiones
        failureRateThreshold: 50      # Si el 50% falla, abre el circuito
        waitDurationInOpenState: 10s  # Espera 10s antes de volver a intentar
        permittedNumberOfCallsInHalfOpenState: 3   # Número de llamadas de prueba en estado HALF_OPEN
        automaticTransitionFromOpenToHalfOpenEnabled: true  # Transición automática de OPEN a HALF_OPEN

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
external:
  api:
    exchange-rate:
      key: 8d51e90dfe027ef9cd10a93f
      url: https://v6.exchangerate-api.com/v6