server:
  port: 9090

spring:
  boot:
    admin:
      context-path: /admin
      # Opcional: Título de la página
      ui:
        title: "PaymentChain Dashboard"

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

# Configuración para que el Admin Server pueda ver los detalles de los otros
management:
  endpoints:
    web:
      exposure:
        include: "*"